services:
  nordvpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nordvpn
    cap_add:
      - NET_ADMIN # Permite al contenedor gestionar configuraciones de red
    ports:
      - 6878:6878        
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}
      - TECHNOLOGY=NordLynx
      - NORDVPN_COUNTRY=ch
      - NORDVPN_GROUP=p2p
      - LAN_DISCOVERY=enable
      - WHITELISTED_SUBNETS=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
      sysctls:
      net.ipv6.conf.all.disable_ipv6: "0"
    restart: unless-stopped
  acestream:
    image: ghcr.io/martinbjeldbak/acestream-http-proxy
    container_name: acestream
    depends_on:
      - nordvpn
    environment:
      - ALLOW_REMOTE_ACCESS=yes    
    network_mode: "container:nordvpn"
    restart: unless-stopped
