services:
  nordvpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    ports:
      - 6878:6878
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN} # Token de autenticación de NordVPN
      - TECHNOLOGY=NordLynx # Tecnología a usar (NordLynx)
      - NORDVPN_COUNTRY=ch # Código del país (CH = Suiza)
      - NORDVPN_GROUP=p2p # Grupo de conexión P2P
      - LAN_DISCOVERY=enable # Habilita LAN Discovery
      - WHITELISTED_SUBNETS=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12 # Subredes permitidas
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "0" # Habilitar soporte para IPv6
    restart: unless-stopped

  acestream:
    image: ghcr.io/martinbjeldbak/acestream-http-proxy
    container_name: acestream
    depends_on:
      - nordvpn # Asegura que NordVPN se inicie antes
    environment:
      - ALLOW_REMOTE_ACCESS=yes # Permite acceso remoto a AceStream
    network_mode: "container:nordvpn" # Usa la red del contenedor NordVPN
    restart: unless-stopped
